name: Docker Image CI

on:
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build the Docker image
        run: IMG=openkruise/kruise-manager:${{ github.ref_name }} & make docker-multiarch
